<?php

/**
 * @file
 * Vopros chat module.
 */

/**
 * Implements hook_menu().
 */
function vopros_chat_menu() {
  $items = array();

  $items['embed/ask-question/chat/%'] = array(
    'title' => 'Chat',
    'page callback' => 'vopros_chat_client_page',
    'page arguments' => array(3),
    // @todo access callback should check that chat id is bound to a question.
    'access callback' => TRUE,
    'file' => 'vopros_chat.pages.inc',
    'delivery callback' => 'vopros_embed_deliver_html_page',
  );

  return $items;
}

/**
 * Implements hook_vopros_question_user_answer_preference().
 *
 * Exposes chat as an user answer preference for questions.
 */
function vopros_chat_vopros_question_user_answer_preference() {
  return array('chat' => t('Chat'));
}
